
export const departments = [
    { id: 'general', name: 'General Physician', icon: 'Stethoscope' },
    { id: 'derma', name: 'Dermatologist', icon: 'Activity' },
    { id: 'dentist', name: 'Dentist', icon: 'Smile' },
    { id: 'cardio', name: 'Cardiologist', icon: 'Heart' },
    { id: 'ortho', name: 'Orthopedist', icon: 'Bone' },
    { id: 'peds', name: 'Pediatrician', icon: 'Baby' },
    { id: 'gynae', name: 'Gynecologist', icon: 'Flower2' },
    { id: 'ent', name: 'ENT Specialist', icon: 'Ear' },
    { id: 'eye', name: 'Ophthalmologist', icon: 'Eye' },
    { id: 'psych', name: 'Psychiatrist', icon: 'Brain' },
];

export const profiles = {
    general: [
        {
            id: 'gen_1',
            name: 'Ramesh Gupta',
            age: 45,
            gender: 'Male',
            occupation: 'Shopkeeper',
            location: 'Mumbai, Maharashtra',
            vitals: { bp: '140/90', heartRate: 88, temp: '99.2·F', weight: '72kg' },
            history: ['Hypertension (5 yrs)', 'Mild Asthma', 'Smoker'],
            symptoms: ['Fatigue', 'Frequent Headaches', 'Chest Heaviness'],
            symptoms_simple: 'I have been feeling very tired lately, frequent headaches, and sometimes my chest feels heavy after lifting boxes.',
            diagnosis_hint: 'Hypertension leading to Angina',
            contraindications: ['Beta-blockers (Asthma Risk)', 'NSAIDs (Gastritis Risk)'],
        },
        {
            id: 'gen_2',
            name: 'Sunita Devi',
            age: 32,
            gender: 'Female',
            occupation: 'Housewife',
            location: 'Lucknow, UP',
            vitals: { bp: '110/70', heartRate: 72, temp: '101.5·F', weight: '58kg' },
            history: ['Penicillin Allergy'],
            symptoms: ['High Fever', 'Shivering', 'Body Ache', 'Pain Swallowing'],
            symptoms_simple: 'I have high fever with shivering since yesterday, body ache, and it hurts when I swallow food.',
            diagnosis_hint: 'Acute Tonsillitis / Viral Fever',
            contraindications: ['Penicillin (Anaphylaxis Risk)', 'Aspirin'],
        }
    ],
    derma: [
        {
            id: 'derma_1',
            name: 'Vikram Singh',
            age: 24,
            gender: 'Male',
            occupation: 'IT Professional',
            location: 'Bangalore, Karnataka',
            vitals: { bp: '120/80', heartRate: 70, temp: '98.6·F', weight: '65kg' },
            history: ['Seasonal Allergies', 'High Stress'],
            symptoms: ['Red Itchy Patches', 'Silver Scales', 'Stress Flares'],
            symptoms_simple: 'I have these red, itchy patches on my elbows and knees. They flake off like silver scales.',
            diagnosis_hint: 'Psoriasis',
            contraindications: ['Systemic Steroids (Rebound Risk)'],
        },
        {
            id: 'derma_2',
            name: 'Anjali Menon',
            age: 19,
            gender: 'Female',
            occupation: 'College Student',
            location: 'Kochi, Kerala',
            vitals: { bp: '110/70', heartRate: 75, temp: '98.4·F', weight: '50kg' },
            history: ['PCOS'],
            symptoms: ['Severe Face Acne', 'Painful Pimples', 'Scarring'],
            symptoms_simple: 'I have severe pimples on my face, especially jawline. They are painful and leave dark marks.',
            diagnosis_hint: 'Acne Vulgaris (Hormonal)',
            contraindications: ['Tetracyclines (Pregnancy Check Needed)', 'Isotretinoin strictly monitored'],
        }
    ],
    dentist: [
        {
            id: 'dent_1',
            name: 'Rajesh Kumar',
            age: 50,
            gender: 'Male',
            occupation: 'Teacher',
            location: 'Delhi',
            vitals: { bp: '130/85', heartRate: 80, temp: '98.6·F', weight: '78kg' },
            history: ['Type 2 Diabetes'],
            symptoms: ['Bleeding Gums', 'Bad Breath', 'Loose Teeth'],
            symptoms_simple: 'My gums bleed when I brush, and my breath smells bad even after brushing. My teeth feel a bit loose.',
            diagnosis_hint: 'Chronic Periodontitis',
            contraindications: ['High Dose Epinephrine (Hypertension Risk)'],
        },
        {
            id: 'dent_2',
            name: 'Priya Sharma',
            age: 28,
            gender: 'Female',
            occupation: 'Marketing Executive',
            location: 'Pune, Maharashtra',
            vitals: { bp: '120/80', heartRate: 76, temp: '98.6·F', weight: '60kg' },
            history: ['Wisdom Tooth Extraction (1yr)'],
            symptoms: ['Sharp Tooth Pain', 'Sensitivity to Cold/Hot'],
            symptoms_simple: 'I have sharp pain in my upper right tooth when I eat ice cream or drink hot tea.',
            diagnosis_hint: 'Dentin Hypersensitivity',
            contraindications: ['Latex Allergy (Dental Equip)'],
        }
    ],
    cardio: [
        {
            id: 'cardio_1',
            name: 'Amitabh Bachchan',
            age: 65,
            gender: 'Male',
            occupation: 'Retired',
            location: 'Kolkata, WB',
            vitals: { bp: '160/95', heartRate: 90, temp: '98.2·F', weight: '85kg' },
            history: ['High Cholesterol', 'Family History Heart Attack'],
            symptoms: ['Breathlessness', 'Chest Squeezing', 'Pain radiating to Left Arm'],
            symptoms_simple: 'I get breathless when walking. Sometimes I feel a squeezing pain in my chest that goes to my left arm.',
            diagnosis_hint: 'Angina Pectoris / CAD',
            contraindications: ['Sildenafil (Nitrate Interaction)'],
        },
        {
            id: 'cardio_2',
            name: 'Meena Iyer',
            age: 55,
            gender: 'Female',
            occupation: 'Bank Manager',
            location: 'Chennai, TN',
            vitals: { bp: '130/80', heartRate: 110, temp: '98.6·F', weight: '70kg' },
            history: ['Hyporthyroidism'],
            symptoms: ['Racing Heart', 'Dizziness', 'Palpitations'],
            symptoms_simple: 'My heart feels like it is racing suddenly even when I am sitting. I feel dizzy sometimes.',
            diagnosis_hint: 'Arrhythmia (AFib)',
            contraindications: ['Caffeine', 'Stimulants'],
        }
    ],
    ortho: [
        {
            id: 'ortho_1',
            name: 'Suresh Patil',
            age: 40,
            gender: 'Male',
            occupation: 'Construction Worker',
            location: 'Nagpur',
            vitals: { bp: '120/80', heartRate: 72, temp: '98.6·F', weight: '68kg' },
            history: ['History of Peptic Ulcer'],
            symptoms: ['Lower Back Pain', 'Radiating Leg Pain', 'Stiffness'],
            symptoms_simple: 'I have severe lower back pain that goes down to my right leg. I cannot bend forward.',
            diagnosis_hint: 'Sciatica',
            contraindications: ['NSAIDs (Bleeding Risk)'],
        },
        {
            id: 'ortho_2',
            name: 'Kamla Das',
            age: 68,
            gender: 'Female',
            occupation: 'Retired Teacher',
            location: 'Bhubaneswar',
            vitals: { bp: '135/85', heartRate: 78, temp: '98.6·F', weight: '75kg' },
            history: ['CKD Stage 3', 'Calcium Deficiency'],
            symptoms: ['Knee Pain', 'Morning Stiffness', 'Difficulty Climbing Stairs'],
            symptoms_simple: 'My knees hurt a lot when I climb stairs. They are stiff in the morning.',
            diagnosis_hint: 'Osteoarthritis',
            contraindications: ['NSAIDs (Renal Toxicity)', 'High Impact Exercise'],
        }
    ],
    peds: [
        {
            id: 'peds_1',
            name: 'Arav Kumar',
            age: 6,
            gender: 'Male',
            occupation: 'Student',
            location: 'Gurgaon',
            vitals: { bp: 'NA', heartRate: 100, temp: '100.2·F', weight: '20kg' },
            history: ['Mild Asthma'],
            symptoms: ['Wheezing Cough', 'Running Nose', 'Mild Fever'],
            symptoms_simple: 'He has a wheezing cough, especially at night. Running nose and mild fever.',
            diagnosis_hint: 'Acute Bronchitis',
            contraindications: ['Aspirin (Reye\'s Syndrome Risk)'],
        },
        {
            id: 'peds_2',
            name: 'Sneha Reddy',
            age: 4,
            gender: 'Female',
            occupation: 'Preschool',
            location: 'Hyderabad',
            vitals: { bp: 'NA', heartRate: 98, temp: '99.0·F', weight: '16kg' },
            history: ['None'],
            symptoms: ['Red Body Spots', 'Itching', 'Recent Fever'],
            symptoms_simple: 'She has small red spots all over her body and is itching a lot. She had fever 2 days ago.',
            diagnosis_hint: 'Chickenpox',
            contraindications: ['Ibuprofen (Necrotizing Fasciitis Risk)'],
        }
    ],
    gynae: [
        {
            id: 'gyn_1',
            name: 'Fatima Sheikh',
            age: 29,
            gender: 'Female',
            occupation: 'Software Engineer',
            location: 'Noida',
            vitals: { bp: '120/75', heartRate: 74, temp: '98.6·F', weight: '62kg' },
            history: ['PCOS', 'History of DVT'],
            symptoms: ['Irregular Periods', 'Weight Gain', 'Chin Hair Growth'],
            symptoms_simple: 'My periods are very irregular. I have gained weight recently and have hair growth on my chin.',
            diagnosis_hint: 'PCOS',
            contraindications: ['Estrogen-containing OCPs (Clot Risk)'],
        },
        {
            id: 'gyn_2',
            name: 'Kavita Joshi',
            age: 35,
            gender: 'Female',
            occupation: 'Teacher',
            location: 'Jaipur',
            vitals: { bp: '110/70', heartRate: 76, temp: '98.6·F', weight: '55kg' },
            history: ['Multiparous (2)'],
            symptoms: ['White Discharge', 'Foul Smell', 'Itching'],
            symptoms_simple: 'I have white discharge with a bad smell and itching in the private area.',
            diagnosis_hint: 'Vaginal Infection / BV',
            contraindications: ['Alcohol (Disulfiram-like reaction with Metronidazole)'],
        }
    ],
    ent: [
        {
            id: 'ent_1',
            name: 'Rahul Verma',
            age: 18,
            gender: 'Male',
            occupation: 'Student',
            location: 'Chandigarh',
            vitals: { bp: '120/80', heartRate: 72, temp: '99.5·F', weight: '60kg' },
            history: ['Swimmer'],
            symptoms: ['Ear Pain', 'Blocked Ear', 'History of Swimming'],
            symptoms_simple: 'My right ear is paining a lot, and it feels blocked. I went swimming yesterday.',
            diagnosis_hint: 'Otitis Externa',
            contraindications: ['Cotton Buds (Avoid Insertion)'],
        },
        {
            id: 'ent_2',
            name: 'Mrs. DSouza',
            age: 45,
            gender: 'Female',
            occupation: 'Singer',
            location: 'Goa',
            vitals: { bp: '130/80', heartRate: 75, temp: '98.6·F', weight: '68kg' },
            history: ['Acid Reflux'],
            symptoms: ['Hoarse Voice', 'Throat Clearing'],
            symptoms_simple: 'My voice has become hoarse. I have to clear my throat constantly.',
            diagnosis_hint: 'Laryngitis / GERD',
            contraindications: ['Whispering (Strains Cords)'],
        }
    ],
    eye: [
        {
            id: 'eye_1',
            name: 'Manoj Tiwari',
            age: 55,
            gender: 'Male',
            occupation: 'Driver',
            location: 'Patna',
            vitals: { bp: '130/85', heartRate: 78, temp: '98.6·F', weight: '72kg' },
            history: ['Diabetes'],
            symptoms: ['Floaters', 'Blurry Central Vision'],
            symptoms_simple: 'I see floating black spots in front of my eyes and my vision is getting blurry specifically in the center.',
            diagnosis_hint: 'Diabetic Retinopathy',
            contraindications: ['Blood Thinners (Bleeding Risk)'],
        },
        {
            id: 'eye_2',
            name: 'Simran Kaur',
            age: 22,
            gender: 'Female',
            occupation: 'Student',
            location: 'Amritsar',
            vitals: { bp: '110/70', heartRate: 74, temp: '98.6·F', weight: '52kg' },
            history: ['Contact Lens User'],
            symptoms: ['Redness', 'Watering', 'Gritty Sensation'],
            symptoms_simple: 'My eyes are very red, watery, and itchy. It feels like there is sand in my eyes.',
            diagnosis_hint: 'Conjunctivitis',
            contraindications: ['Contact Lenses (Discontinue Use)'],
        }
    ],
    psych: [
        {
            id: 'psych_1',
            name: 'Arjun Das',
            age: 27,
            gender: 'Male',
            occupation: 'Corporate Job',
            location: 'Bangalore',
            vitals: { bp: '130/85', heartRate: 95, temp: '98.6·F', weight: '70kg' },
            history: ['Family Depression History'],
            symptoms: ['Insomnia', 'Persistent Sadness', 'Anhedonia', 'Fatigue'],
            symptoms_simple: 'I cannot sleep at night. I feel sad all the time and have lost interest in my hobbies.',
            diagnosis_hint: 'Depression',
            contraindications: ['Alcohol (Depressant Interaction)'],
        },
        {
            id: 'psych_2',
            name: 'Rohan Mehta',
            age: 21,
            gender: 'Male',
            occupation: 'Student',
            location: 'Mumbai',
            vitals: { bp: '120/80', heartRate: 88, temp: '98.6·F', weight: '65kg' },
            history: ['None'],
            symptoms: ['Panic Attacks', 'Palpitations', 'Fear of Crowds'],
            symptoms_simple: 'I get sudden attacks of fear where my heart pounds. It happens in crowded places.',
            diagnosis_hint: 'Panic Disorder',
            contraindications: ['Caffeine (Triggers Panic)'],
        }
    ]
};
